server:
 port: 9001
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/hotelservices
  username: postgres
  password: root
 
 jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   
  
     
     
     