select * from dba_tables;

desc ALL_USERS;
SELECT USERNAME FROM ALL_USERS 
    WHERE USERNAME='APP_DEV_USER';
    
--ALTER USER
alter user hr identified by hr account unlock;
 alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER SecurityBasic IDENTIFIED BY ifms;
GRANT CONNECT, RESOURCE TO SecurityBasic;
GRANT CREATE ANY EDITION,UPDATE ANY TABLE, DROP ANY EDITION to SecurityBasic;
GRANT UNLIMITED TABLESPACE TO SecurityBasic;

SELECT USERNAME FROM ALL_USERS 
    WHERE USERNAME='app_user';
    
--ALTER SESSION IS IMPORTANT BEFORE CREATING USER
 alter session set "_ORACLE_SCRIPT"=true;  
 CREATE USER APP_DEV_USER IDENTIFIED BY DEV_USER_PWD;
GRANT CONNECT, RESOURCE TO APP_DEV_USER;
GRANT CREATE ANY EDITION,UPDATE ANY TABLE, DROP ANY EDITION to APP_DEV_USER;

SELECT * FROM TABLES;

--create user for app
alter session set "_ORACLE_SCRIPT"=true;  --cannot create without altering the session
CREATE USER app_user IDENTIFIED BY appuserpwd;
GRANT CONNECT, RESOURCE TO app_user;
GRANT CREATE ANY EDITION,UPDATE ANY TABLE, DROP ANY EDITION to app_user;


--
show user;
desc GREETING;
select * from GREETING;

CREATE TABLE EMP_FAMILY_MEMBER
(
ID NUMBER(10),
EMP_ID NUMBER(10),
NAME VARCHAR(50),
DOB TIMESTAMP(3),
PERCENTAGE_DISABILITY NUMBER(10),
NOMINEE NUMBER(1),
SI_NOMINATION VARCHAR(50),
RELATIONSHIP VARCHAR(50),
MARITAL_STATUS VARCHAR(10),
DEPENDENT  NUMBER(1),
GRATUITY_NOMINATION VARCHAR(50),
GIS_NOMINATION VARCHAR(50),
GENDER VARCHAR(6),
PHYSICALLY_DISABLED VARCHAR(50),
EMPLOYED NUMBER(1),
PF_NOMINATION VARCHAR(50),
GPF_NOMINATION VARCHAR(50),
PRIMARY KEY (ID));
)